packages:
    - apps/**
    - modules/**
    - packages/**

onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@prisma/engines"
    - esbuild
    - netlify-cli
    - prisma
    - sharp
    - unix-dgram
